---
apiVersion: 1
contactPoints:
  - orgId: 1
    name: google-chat
    receivers:
      - uid: google-chat
        type: googlechat
        settings:
          url: https://chat.googleapis.com/v1/spaces/AAQAnD9uZ2Q/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=oW4ElcVVoI3UohUeCSkOYlPBao_YyBxok-boOJPPgW4
        disableResolveMessage: false
