---
services:

  dev-alloy:
    image: grafana/alloy:v1.11.3
    container_name: dev-alloy
    restart: unless-stopped
    environment:
      # additional data which should be available in config.alloy
      - HOSTNAME=${HOSTNAME}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./config/alloy/config-dev.alloy:/etc/alloy/config.alloy:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    ports:
      - 2345:12345
    extra_hosts:
      - "host.docker.internal:host-gateway"
