---
name: 'Housekeeping: Labels'

on:
  schedule:
    - cron: '0 1 * * *' # https://crontab.guru
  push:
    branches:
      - main
    paths:
      - .github/workflows/housekeeping-labels.yml

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  housekeeping-labels:
    uses: sommerfeld-io/.github/.github/workflows/housekeeping-labels.yml@main
